-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create Cases Table
create table public.cases (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status text default 'Intake',
  
  -- Caller Info
  caller_name text,
  caller_phone text,
  caller_email text,
  caller_relationship text,
  call_datetime timestamp with time zone,

  -- Defendant Info
  defendant_name text,
  defendant_dob text,
  defendant_booking_number text,
  case_number text,
  charges text[], -- Array of strings
  bond_amount text,
  jail_location text,

  -- Court Info
  court_type text,
  county text,
  district text,
  justice_court text,
  form_number text,
  bondsman_name text,

  -- Payment Info
  total_owed text,
  payment_plan_amount text,
  payment_frequency text,

  -- Notes
  notes text
);

-- Create Contacts Table
create table public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  case_id bigint references public.cases(id) on delete cascade,
  
  name text,
  phone text,
  email text,
  address text,
  city text,
  state text,
  zip text,
  ownership text,
  
  employer text,
  employer_phone text,
  employer_city text,
  employer_state text,
  employer_zip text,
  employer_contact text,
  occupation text
);

-- Create Documents Table
create table public.documents (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  case_id bigint references public.cases(id) on delete cascade,
  
  name text,
  type text,
  url text,
  storage_path text
);

-- Set up Row Level Security (RLS)
-- For development, we will allow public access. 
-- IN PRODUCTION, YOU SHOULD RESTRICT THIS.
alter table public.cases enable row level security;
alter table public.contacts enable row level security;
alter table public.documents enable row level security;

create policy "Enable all access for all users" on public.cases
for all using (true) with check (true);

create policy "Enable all access for all users" on public.contacts
for all using (true) with check (true);

create policy "Enable all access for all users" on public.documents
for all using (true) with check (true);

-- Create Storage Bucket for Documents
insert into storage.buckets (id, name, public) values ('documents', 'documents', true);

create policy "Public Access" on storage.objects for all using ( bucket_id = 'documents' );
